const ActionTypes = {
    CURRENT_USER_DATA: "CURRENT_USER_DATA",
    ALL_USER_LIST: "ALL_USER_LIST",
    REQUEST_LIST: "REQUEST_LIST",
    MY_REQUEST_ACTION:"MY_REQUEST_ACTION",
}

export default ActionTypes